services:
    web:
        build:
            context: .
        container_name: "web"
        restart: always
        command: bash ./entrypoint.sh
        volumes:
            - .:/usr/src/app
            - ./static:/usr/src/app/static
        ports:
            - 8000:8000
        networks:
            - my_network
        depends_on:
            - db

    db:
        image: postgres:15-alpine
        container_name: "db"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        restart: always
        env_file: .env.dev


networks:
    my_network:

volumes:
    static:
    postgres_data: